name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24dd370e38a79e0883618b93c467a3d317fb6569683d6311809d2a87ef559346"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
