name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5133c1aad2361c8432445370d7bf6a65b16cbc31321dfbed5425c6752c811e83"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
