name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc319e93588bdf8d4ce3765e79b4fc92886ff76e1f2756bde0912c5b39f413cd"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
