name = "Rexcliffe MTR Packwiz"
author = "RX"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e7e513250fbf2cf66f28330d67d482b20bc16141597b64ccdc3510664a21637"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
