name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09f128ab7405d391822ddf0a5171345368a6fe9b458b20c60dcd19fd53578809"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
