name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "123abba98e80b414f926312c6b2bd43b2a1b1cb92939d12b24a09e7bbec0a95a"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
