name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "929782848228f36729dd5ee3ea066fcff2c718a1a0e5be85baa6bd8e330fecf0"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
