name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2774221f6a29689aba36dcc6a8c4b9d016c598813b3bece1249925a7eba8941b"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
