name = "Rexcliffe MTR Packwiz"
author = "RX"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9458735bc81b4a079f305c8c0ddf734a8c750a7fc5f88880892f704812028599"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
