name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77fbc610a7944905e480d827b8c9fd37eed1e6e2d1161485cfdadcffedd2d572"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
