name = "Rexcliffe MTR Packwiz"
author = "RX"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db6dd270b7555a168141fcf2e53095727ae86bcb8018ab1f15f1897498872224"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
