name = "Rexcliffe MTR Packwiz"
author = "RX"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e14594522b9c0ba1e833914e01077fa9274ad35ac5a3d6004a4bf2068cbd784c"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
