name = "Rexcliffe MTR Packwiz"
author = "RX"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6fad9f9d4646de311711baa12cf17bcbda5ed66974db7dd6bcd3ba630b77286a"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
