name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc497281521c0316ee65c919d00fb5df64f4cae9167bd203eabccc2c5600356f"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
