name = "Rexcliffe MTR Packwiz"
author = "RX"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5bb64245c33450cfe0e2554e5eeb8bb42d12d8eae8dcb068ab78e9a77c5b4492"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
