name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f09c5747758dc3c13874c315a53a3b4bf782376484345e82bcc18cbdf0aa398"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
